### ISSUE TITLE
include trikznobug

### ISSUE THREAD

**Issue by Smesh292** [1ci/trikz-fixes#1]
//// trikz_fix_csgo.sp
//
// trikz_fix_csgo.sp(7) : fatal error 183: cannot read from file: "trikznobug"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0,16 sec
// ----------------------------------------

**Comment by 1ci** [comment]
Added missing files.

This project is not maintained by the way. George and I worked on it a couple of years ago. The script can be improved and should actually use the flashbang elasticity constant in the game engine to determine speed, which I believe was 0.35 or something along that. There was a guy who did an overall better job at it, however I can't seem to find his repo on github. He might have privated it. Anyway, hopefully you can take whatever you need from this, improve it and alter it to your needs.
